### PR TITLE
Carve up __main__ into modules (pass 1)

### PR DESCRIPTION
**Pull request by gwax**
This PR does the following:

- Carve a bunch of functionality out of `__main__.py` to separate modules in anticipation of future refactoring / improvements.
  - This is a first pass and is meant to be better than a single monolithic `__main__.py` but by no means perfect.
- Replace globals with `contextvars.ContextVar`
- Per module `LOGGER` objects
- Run [black](https://github.com/ambv/black) against everything because I am too lazy to lint by hand

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I appreciate the PR, you've saved me a lot of hassle! I will get a chance to review this ins the next few days (doing a lot of work/traveling in the early parts of the week).

Thanks for always being there, @gwax :)

**Comment by ZeldaZach** [comment]
Thanks for doing this, @gwax! You've saved me a lot of hassle to get the initial design patterns in place. I will get a chance to properly review it in the next few days (I'm currently working very hard for school & traveling a lot in the early week). Thanks for always being there :)

**Comment by ZeldaZach** [comment]
Thanks for doing this, @gwax! You've saved me a lot of hassle to get the initial design patterns in place. I will get a chance to properly review it in the next few days (I'm currently working very hard for school & traveling a lot in the early week). Thanks for always being there :)

**Comment by ZeldaZach** [comment]
Thanks for doing this, @gwax! You've saved me a lot of hassle to get the initial design patterns in place. I will get a chance to properly review it in the next few days (I'm currently working very hard for school & traveling a lot in the early week). Thanks for always being there :)

**Comment by ZeldaZach** [comment]
Thanks for doing this, @gwax! You've saved me a lot of hassle to get the initial design patterns in place. I will get a chance to properly review it in the next few days (I'm currently working very hard for school & traveling a lot in the early week). Thanks for always being there :)

**Comment by ZeldaZach** [comment]
Thanks for doing this, @gwax! You've saved me a lot of hassle to get the initial design patterns in place. I will get a chance to properly review it in the next few days (I'm currently working very hard for school & traveling a lot in the early week). Thanks for always being there :)

**Comment by ZeldaZach** [comment]
Thanks for doing this, @gwax! You've saved me a lot of hassle to get the initial design patterns in place. I will get a chance to properly review it in the next few days (I'm currently working very hard for school & traveling a lot in the early week). Thanks for always being there :)

**Comment by ZeldaZach** [comment]
(Sorry it spammed out; Not sure what happened)

**Comment by gwax** [comment]
No worries; GitHub has been having some issues. :(

**Comment by gwax** [comment]
This PR should probably wait on #99 and then be updated before proper review

**Pull request merged**
