### PR TITLE
Improve CI stability and performance

### PR DESCRIPTION
**Pull request by gwax**
- Pre-install unicode-data to prevent install install failures on install of `unicode` from npm
- Enable caching of `node_modules` to speed up module install and compilation of underlying features

### CODE REVIEW

**Comment by tooomm** [comment]
Can you try to rerun the build and check the cache part?
Maybe you have to reset it as well.

**Comment by gwax** [comment]
I have built this a few times, the cache seems to work out just fine.

**Comment by tooomm** [comment]
speaking about travis cache: https://travis-ci.org/mtgjson/mtgjson/jobs/252282033#L304

**Comment by gwax** [comment]
@tooomm that is fine and to be expected, the cache exists per branch and is purely an optimization. The build works entirely fine without it but takes 30s-2m less time to build with it.

**Comment by tooomm** [comment]
@gwax it's also on a pr-basis as seen here: https://travis-ci.org/Cockatrice/Magic-Spoiler/caches
If you check the cache for mtgjson repo there is none... so uploading also doesn't work despite stated different in the travis build.

Maybe build branches is turned of in the mtgjson repo settings in travis? I think that's requiered to make caching work!

**Comment by gwax** [comment]
- It is speeding up the builds on my fork and it will speed up the builds in anyone else's forks.
- Build branch updates is turned on for mtgjson/mtgjson.
- The cache is visible for my PR in travis: https://travis-ci.org/mtgjson/mtgjson/caches
- In the PR build history, you will see that subsequent builds of that PR are faster: https://travis-ci.org/mtgjson/mtgjson/pull_requests

And, **MOST** importantly:

- the stupid unicode package error that is causing almost all builds to fail is gone

**Comment by tooomm** [comment]
We are back on trusty soon: https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

No idea what you changed @gwax, but it's working now and Travis time went also down for the subsequent build on this PR. On master it looks also good 👍 
Did you just rerun as I requested first?

>Build branch updates is turned on for mtgjson/mtgjson.

Just double checking 👍 
If I remember correctly, it's a requirement.

>The cache is visible for my PR in travis: https://travis-ci.org/mtgjson/mtgjson/caches

It looks like people without write access to the repo don't see the proper cache page? I still get the "no cache setup" info

**Pull request merged**
