### PR TITLE
Patch Gatherer regressions, remove bad translations and provide text for Homura's Essence in SOK

### PR DESCRIPTION
**Pull request by bakert**
This PR works around the following problems:

+ Gatherer currently has the wrong text on the printing tab for the flip side of several SOK flip cards.
+ Gatherer currently has no rules text for Homura's Essence.
+ We previously had the translation of the flip side of several flip cards as the name for both the flip side and the front side. Now the front side gets the correct English name instead of the wrong translation. (It would be better and easy to use real translations if we have those archived anywhere.)

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Thanks for the fix! If possible can you also put these changes into our setConfigs so they are auto populated and not lost on a full rebuild?

**Comment by bakert** [comment]
`shared/set_configs/SOK.json` has the necessary patches in commit 880e8ae which is part of this PR. You can see it down the bottom of https://github.com/mtgjson/mtgjson/pull/503/commits/880e8ae32791c7eabbb23e87793696e8f36e015d

Is that the right way to do it?

**Comment by ZeldaZach** [comment]
Haha yeah that's correct. Didn't see the 2nd file modified! Can you update the changelog too? :)

**Comment by bakert** [comment]
:)

Added changelog.json changes.

**Pull request merged**
