### PR TITLE
Add missing possible card layout value

### PR DESCRIPTION
**Pull request by pipe01**
I'm not sure how to add the change to the changelog, sorry.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
To modify the changelog, simply open changelog.json in the web folder and add a new json object to the top of the file. You can copy/paste the old one and just replace the values.

**Comment by pipe01** [comment]
What version should it be?

**Comment by ZeldaZach** [comment]
Since it's a minor change, increment the last number (3.19.3) 😄

**Comment by pipe01** [comment]
There you go

**Pull request merged**
