### PR TITLE
switched print statement to f strings

### PR DESCRIPTION
**Pull request by rohitmusti**
Just updating your print statement to an f-string. It is a slightly faster print from python3 and slightly more readable!

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Oo didn't know about this, thanks for pointing it out! If you'd like to update all of the strings, please feel free to. If not, I can get that done shortly :)

**Comment by rohitmusti** [comment]
sure, I'll update the PR

**Comment by rohitmusti** [comment]
yeah! I'll update the rest update the PR!

**Comment by ZeldaZach** [comment]
Oh and make sure Travis likes you, otherwise I can't merge it in 😄

**Comment by skwerlman** [comment]
looks like pylint needs to be configured to allow fstrings; the check `logging-fstring-interpolation` should be added to the disable list

**Comment by rohitmusti** [comment]
ok, i'll add it in. thanks for the feedback!

**Comment by ZeldaZach** [comment]
Make sure to run Tox so your PR gets travis approved. It should auto-run black and some linters to cleanup the work :)

**Comment by ZeldaZach** [comment]
Thanks for your help with this issue! I hope you stick around the project :)

**Pull request merged**
