### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by silasary**

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Is this how a python package lists dependencies outside of normal python scope?

**Comment by AridTag** [comment]
[seems that way](https://pip.pypa.io/en/latest/user_guide/#requirements-files)

**Comment by silasary** [comment]
Yup. It's the way you share pypy dependencies with other developers/users.

>

**Comment by ZeldaZach** [comment]
Sounds good to me. Are we sure these are the only dependencies (so far)?

**Comment by silasary** [comment]
So far, yes.
To make it, I created an empty virtual environment, then added packages until it started working.

**Pull request merged**
