### PR TITLE
Full rebuild

### PR DESCRIPTION
**Pull request by fenhl**
No changes to code, just a full rebuild of the JSON.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I ask that you rebuild once 3.11.1 gets merged (which will either be my PR or G's). I won't close this PR, but you're free to either update it or make a new one.

**Comment by fenhl** [comment]
You mean 3.11.0?

**Comment by ZeldaZach** [comment]
No, 3.11.1 will be the Lint validations

**Comment by ZeldaZach** [comment]
No, 3.11.1. I just merged that PR so you're free to offer a full rebuild using that code base and we'll work from there 👍

**Pull request merged**
