### PR TITLE
Fixes #342 - add block to SetList.json

### LINKED ISSUE #342: Add BlockList.json or add "block" field to SetList.json
While each set object in **AllSets.json** has a block field, this field isn't present in **SetList.json**.
Having this field is very useful for organizing sets by block and allows developers to not to have to hardcode that information.

Alternatively, a new file called **BlockList.json** could organize sets by blocks in the following format:

```
[
    {
        "name": "block name",
        "sets": [
            {
                "name": "Set Name",
                "code": "SET",
                "releaseDate": "2017-05-13"
            },
           ...
        ]
    },
    ...
]
```

In addition to having **BlockList.json**, having **StandardBlockList.json**, which contains only the sets in standard, could also prove useful to some apps, like those geared towards writing deck lists.

### PR DESCRIPTION
**Pull request by KMontag42**
Only thing I wasn't sure of, is how you would want to handle sets that don't have a block, `UGL` for instance.

I can put whatever you would like there ^_^

### CODE REVIEW

**Comment by KMontag42** [comment]
ah changelog, i will update that now ^_^

looks like I should also commit the newly built sets? I can do that as well.

**Comment by ZeldaZach** [comment]
Looks nice to me. If JSON returns something and it's null, we should just say so.

**Comment by KMontag42** [comment]
Hurray! Let me know if there is anything else you'd like me to update before merging ^_^

**Comment by ZeldaZach** [comment]
Looks good to me!

**Pull request merged**
